FROM node:20.11.1-bookworm-slim AS base
WORKDIR /src/backend
COPY ./backend/package.json ./
COPY ./backend/yarn.lock ./
RUN yarn
COPY ./backend .

FROM base as builder
WORKDIR /src/backend
RUN yarn build

FROM node:20.11.1-bookworm-slim
WORKDIR /src/backend
COPY ./backend/package.json ./
COPY ./backend/yarn.lock ./
RUN yarn install --prod
COPY --from=builder src/backend/dist ./
EXPOSE 3000

