FROM node:20.11.1-bookworm-slim AS base
WORKDIR /src/frontend
COPY ./frontend/package.json ./
COPY ./frontend/yarn.lock ./
RUN yarn
COPY ./frontend .

FROM base AS builder
WORKDIR /src/frontend
RUN yarn build

FROM nginx:1.25.4 as main
WORKDIR /src/frontend
COPY --from=builder /src/frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]