name: Backend image Build and Push

on:
  push:
    branches: [main, dev]

jobs:
  prod:
    name: PROD ENV
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and Push Docker image
        run: |
          docker build -f Dockerfile.express -t karnaankit/repo-backend:stable -t karnaankit/repo-backend:$(git rev-parse --short "$GITHUB_SHA") .
          docker push karnaankit/repo-backend:stable
          docker push karnaankit/repo-backend:$(git rev-parse --short "$GITHUB_SHA")

      - name: Commit version increase
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          token: ${{ secrets.GIT_TOKEN }}

      - name: Commit version increase
        run: |
          git config --global user.name 'karnaankit'
          git config --global user.email 'karna.ankit1@gmail.com'
          cd backend
          npm version patch -m "Increase backend version to %s"
          cd ..
          git commit -am "Increased version"
          git push https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/karnaankit/runner.git HEAD:main
          
  dev:
    name: DEV ENV
    runs-on: self-hosted
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and Push Docker image
        run: |
          docker build -f Dockerfile.express -t karnaankit/repo-backend:dev -t karnaankit/repo-backend:$(git rev-parse --short "$GITHUB_SHA") .
          docker push karnaankit/repo-backend:dev
          docker push karnaankit/repo-backend:$(git rev-parse --short "$GITHUB_SHA")
