name: Deploy Frontend to S3/CloudFront

on:
  push:
    branches:
      - frontend 

jobs:
  build_and_deploy:
    runs-on: self-hosted 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Upload to S3
        run: |
          cd frontend
          aws s3 sync ./build * s3://frontend-ankit

      - name: Invalidate CloudFront distribution
        run: aws cloudfront create-invalidation --distribution-id EW439PCCRFST9 --paths "/*"
