name: Deploy Frontend to S3/CloudFront

on:
  push:
    branches:
      - frontend 

jobs:
  build_and_deploy:
    runs-on: self-hosted 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies and build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Upload to S3
        run: |
          cd frontend
          aws s3 cp dist s3://frontend-ankit --recursive

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"

      - name: Commit version increase
        env:
          PAT: ${{ secrets.GIT_TOKEN }}
        run: |
          git config --global user.name 'karnaankit'
          git config --global user.email 'karna.ankit1@gmail.com'
          cd backend
          npm version patch
          cd ..
          git commit -am "Increased version"
          git push https://x-access-token:${PAT}@github.com/${GITHUB_REPOSITORY}.git
